@startuml
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}

package HotelQ {
    rectangle "HotelQ Service" <<Application>> as HotelQService {
        HotelQService : /hotels <<Path>>
    }

    class Hotels <<Resource>> {
        + getHotels() : Hotel <<GET>>
        + createHotel() : Hotel <<POST>>
    }

    class HotelResource <<Resource>> {
        + getHotel() : Hotel <<GET>>
        + updateHotel() : Hotel <<PUT>>
        + deleteHotel() : void <<DELETE>>
    }

    class Hotel <<Representation>> {
        - name
        - address
        - district
        - province
        - postalcode
        - tel
        - region
    }

    HotelQService --> Hotels
    Hotels --> HotelResource : "/{hotelId} <<Path>>"
    HotelResource ..> Hotel : "<<use>>"
}
@enduml
